### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by gagarski** [camper9993/Transpose#1]
1. Никаких абсолютных путей к файлам на вашем компьютере в исходниках и тестах быть не должно.
2. Туда же. Зависимости в проект лучше добавлять не из локального JAR файла, а из Maven. Так не придётся совершать дополнительные манипуляции чтобы запустить ваш проект.
3. Тесты должны не печатать что-то на консоль, а проверять корректность программы и падать, если результат не соответствует ожидаемому.
4. Сравнивать строки с помощью `==` и `!=` в Джаве нельзя. Вы это делаете везде. Среда разработки вас об этом везде предупреждает.
5. Почему `void writeTo(String ofile)` что-то печатает в консоль?
6. Почему метод `void writeText(BufferedReader reader)` принимает reader?
7. Код для печати в консоль/файл и для чтения из консоли/файла должен быть общим. Отличаться должно только создание readerа/writerа/потока.
8. Вместо циклов по индексу лучше использовать циклы for-each.
9.     private LinkedHashMap<Integer, ArrayList<String>> text = new LinkedHashMap<>();
Почему именно такая структура данных?

**Comment by camper9993** [comment]
Вроде все исправил кроме 5 - 7, можете по подробнее объяснить суть 5 - 7, так и не разобрался что нужно исправить.
И еще после того как как библиотеку org.junit.jupiter.api добавили через зависимости в pom.xml в тестах появилась такая ошибка
 java.lang.NoSuchMethodError: org.junit.jupiter.api.extension.ExtensionContext.getTestInstanceLifecycle()Ljava/util/Optional;
Как это исправить?

**Comment by gagarski** [comment]
№5 - программа должна печатать что-то в консоль только когда не задан выходной файл.
№6 - меня смущала только комбинация названия метода и аргумента
№7 - для чтения у вас что-то близкое к истине. Если вы избавитесь от приглашения для ввода, то у вас в двух ветках в конструкторе будет почти одинаковый код. Можно оставить ветвление только для создание `Reader`а. Что ещё хотелось бы по этому поводу:
 - таким же образом организовать логику для вывода
 - вытащить логику создания входного/выходного потока в `TransporterLauncher`
 - вместо пустой строки в качетсве "особого" значения использовать null.


Ещё:

1. В `leftSide` и `ridghtSide`:  добавлять пробелы по одному в цикле с помощью конкатенации крайне неээфективно. Нельзя ли как-то посчитать сколько пробелов нужно добавить и добавить их один раз?
2. Не станет ли жизнь сильно проще, если `transposeText` будет двумерным массивом?
3. Без флагов `-r`, `-r` и `-a`, `length` в `TransporterLauncher` будет равен -1. Вы уверены что программа будет работать корректно? Лучше бы добавить тесты, запускающие `TransporterLauncher` с разными наборами аргументов.

**Comment by gagarski** [comment]
> И еще после того как как библиотеку org.junit.jupiter.api добавили через зависимости в pom.xml в тестах появилась такая ошибка
java.lang.NoSuchMethodError: org.junit.jupiter.api.extension.ExtensionContext.getTestInstanceLifecycle()Ljava/util/Optional;
Как это исправить?

У меня сейчас ваши тесты запускаются. Надо смотреть на вашем компьютере.

**Comment by camper9993** [comment]
Опять не могу скомпилировать jar файл который собрал Maven, пишет что нет библиотеки args4j, хотя в  pom.xml в зависимостях эта библиотека указана(

**Comment by gagarski** [comment]
> Без флагов -r, -r и -a, length в TransporterLauncher будет равен -1. Вы уверены что программа будет работать корректно? Лучше бы добавить тесты, запускающие TransporterLauncher с разными наборами аргументов.

Это всё ещё актуально.

Сейчас у меня не проходят все ваши тесты (падают с `AssertionFailedError`).

По поводу мейвеновской сборки: у меня нет проблем с `args4j`, но есть с JUnit. Пришлось сделать следующее:
1. Добавить зависимости:
```xml
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <version>5.2.0</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-engine</artifactId>
            <version>5.2.0</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.vintage</groupId>
            <artifactId>junit-vintage-engine</artifactId>
            <version>5.2.0</version>
            <scope>test</scope>
        </dependency>
```
2. Изменить раскладку файлов на привычную для Maven:
```
src
├── main
│   └── java
│       ├── console_app
│       │   ├── 1
│       │   ├── 2
│       │   ├── 3
│       │   ├── Transporter.java
│       │   └── TransporterLauncher.java
│       └── META-INF
│           └── MANIFEST.MF
└── test
    └── java
        └── console_app
            └── TransporterTest.java
```
3. Для полной красоты добавить в секцию plugins:
```
            <plugin>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.21.0</version>
                <dependencies>
                    <dependency>
                        <groupId>org.junit.platform</groupId>
                        <artifactId>junit-platform-surefire-provider</artifactId>
                        <version>1.2.0</version>
                    </dependency>
                </dependencies>
            </plugin>
```
Это конфигурация плагина, запускающего тесты перед сборкой.

После этого при запуске `mvn package` у меня получается джарник, который запускается нормально (если пропустить падающие тесты).
[Привожу итоговый pom.xml](https://gist.github.com/gagarski/4be6d54b6a4240b5d10ab920f3a95672)
